version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8008:8008"
    environment:
      - QUARKUS_PROFILE=prod
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
