services:
  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8443:8443"
    env_file:
      - /root/.secrets/.env
    volumes:
      - /etc/ssl/:/etc/ssl/
      - file_data:/data/disk
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - /etc/ssl/:/etc/ssl/

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8543:8443"
    env_file:
      - /root/.secrets/.env
    volumes:
      - keycloak_data:/opt/keycloak/data
      - /etc/ssl/:/etc/ssl/
    command: start --https-key-store-file=/etc/ssl/jung-garde.ch/keycloak-keystore.jks --https-key-store-password=J2WV65C3PB3T094QDKgMfv3e42xfA213 --https-key-alias=keycloak
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
  file_data:
  keycloak_data:
