quarkus:
  oidc:
    auth-server-url: https://jung-garde.ch:8543/realms/quarkus
    client-id: backend-service
    credentials:
      secret: ${KC_SECRET}
  keycloak:
    policy-enforcer:
      enable: true
      lazy-load-paths: true
  mongodb:
    database: jung-garde
    connection-string: mongodb://mongodb:27017
    credentials:
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
  http:
    root-path: /jung-garde
    ssl:
      certificate:
        files: /etc/ssl/certs/fullchain.pem
        key-files: /etc/ssl/private/jung-garde-key.key
    cors:
      ~: true
      origins:
        - "https://jung-garde.ch"

variable:
  path:
    disk: /data/disk/