quarkus:
  mongodb:
    database: jung-garde
    connection-string: mongodb://${DB_HOST}:27017
    credentials:
      username: "user"
      password: ${MONGO_PASSWORD}
  http:
    port: 8080
    root-path: /jung-garde