quarkus:
  mongodb:
    database: jung-garde
    connection-string: mongodb://localhost:27017
    credentials:
      username: "myuser"
      password: "password"
  http:
    port: 8080
    root-path: /jung-garde
  container-imag:
    build: true