quarkus:
  mongodb:
    database: jung-garde
    connection-string: mongodb://localhost:27017
    credentials:
      username: "user"
      password: ${MONGO_PASSWORD}
  http:
    port: 8080
    root-path: /jung-garde
    cors:
      ~: true
      origins:
        - "https://jung-garde.ch"

variable:
  path:
    disk: /data/disk/