quarkus:
  oidc:
    auth-server-url: http://localhost:8080/realms/quarkus
    client-id: backend-service
    credentials:
      secret: secret
    tls:
      verification: none

  keycloak:
    policy-enforcer:
      enable: true
  mongodb:
    database: jung-garde
    connection-string: mongodb://localhost:27017
    credentials:
      username: "myuser"
      password: "password"
  http:
    auth:
      policy:
        authenticated:
          policy: authenticated
    port: 9090
    root-path: /jung-garde
    limits:
      max-body-size:
        650M
    cors:
      ~: true
      origins:
        - "http://localhost:4200/"

variable:
  path:
    disk: src/main/resources/tmp/