quarkus:
  mongodb:
    database: jung-garde
    connection-string: mongodb://mongodb:27017
    credentials:
      username: "user"
      password: ${MONGO_PASSWORD}
  http:
    port: 8080
    root-path: /jung-garde
    insecure-requests: redirect
    ssl:
      certificate:
        files: /etc/ssl/certs/fullchain.pem
        key-files: /etc/ssl/private/jung-garde-key.key
    limits:
      max-body-size: 650M
    cors:
      ~: true
      origins:
        - "https://jung-garde.ch"