quarkus:
  mongodb:
    database: jung-garde
    connection-string: mongodb://host.docker.internal:27017
    credentials:
      username: "user"
      password: ${MONGO_PASSWORD}
  http:
    cors:
      ~: true
      origins: "http://localhost:4200"
      methods: GET,PUT,POST,DELETE