quarkus:
  keycloak:
    policy-enforcer:
      enable: true
      lazy-load-paths: true
  mongodb:
    database: jung-garde
    connection-string: mongodb://mongodb:27017
    credentials:
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
  http:
    root-path: /jung-garde
    limits:
      max-body-size: 650M
    ssl:
      certificate:
        files: /etc/ssl/certs/fullchain.pem
        key-files: /etc/ssl/private/jung-garde-key.key
    cors:
      ~: true
      origins:
        - "https://jung-garde.ch"
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated
  oidc:
    auth-server-url: https://jung-garde.ch:8543/realms/quarkus
    client-id: backend-service
    credentials:
      secret: ${KC_SECRET}
    token:
      audience: account

mp:
  jwt:
    verify:
      issuer: https://jung-garde.ch:8543/realms/quarkus
      publickey:
        location: https://jung-garde.ch:8543/realms/quarkus/protocol/openid-connect/token

variable:
  path:
    disk: /data/disk/
